INSERT INTO user (email, password, role, username) VALUES ("emailaddress1@random.com", "password", "USER", "name1");
INSERT INTO user (email, password, role, username) VALUES ("emailaddress2@random.com", "password", "USER", "name2");
INSERT INTO user (email, password, role, username) VALUES ("emailaddress3@random.com", "password", "USER", "name3");
INSERT INTO user (email, password, role, username) VALUES ("doesnotexist@anonymous.com", "password", "USER", "Anonymous");
INSERT INTO question (created, modified, text, user_id) VALUES ("2017-07-28", "2017-07-28", "Do I need to backup my data with QuickBooks Online?", 1);
INSERT INTO question (created, modified, text, user_id) VALUES ("2017-07-28", "2017-07-28", "This is Question 2", 2);
INSERT INTO question (created, modified, text, user_id) VALUES ("2017-07-28", "2017-07-28", "This is Question 3", 1);
INSERT INTO answer (created, modified, question_id, text, user_id, accepted) VALUES ("2017-07-28", "2017-07-28", 1, "No, QuickBooks does it for you", 3, 0);
INSERT INTO answer (created, modified, question_id, text, user_id, accepted) VALUES ("2017-07-28", "2017-07-28", 1, "No, QuickBooks Online automatically backs up your data for you with bank-level security.", 2, 1);
INSERT INTO answer (created, modified, question_id, text, user_id, accepted) VALUES ("2017-07-28", "2017-07-28", 1, "This is Answer 2", 3, 0);
INSERT INTO comment (created, modified, text, type, user_id) VALUES ("2017-07-28", "2017-07-28", "Which parts of the data?", 2, 3);
INSERT INTO comment (created, modified, text, type, user_id) VALUES ("2017-07-28", "2017-07-28", "All of it", 2, 1);
INSERT INTO comment (created, modified, text, type, user_id) VALUES ("2017-07-28", "2017-07-28", "Physically or in a cloud?", 1, 1);
INSERT INTO comment (created, modified, text, type, user_id) VALUES ("2017-07-28", "2017-07-28", "Where is it stored?", 1, 1);
INSERT INTO comment (created, modified, text, type, user_id) VALUES ("2017-07-28", "2017-07-28", "Your data is saved to two hard drives. Intuit copies all data periodically to a third party hard drive in order to protect your data in case something happens to the first two hard drives.", 1, 2);
INSERT INTO comment_question (question_id, comment_id) VALUES (1, 1);
INSERT INTO comment_question (question_id, comment_id) VALUES (1, 2);
INSERT INTO comment_answer (answer_id, comment_id) VALUES (1, 3);
INSERT INTO comment_answer (answer_id, comment_id) VALUES (2,4 );
INSERT INTO comment_answer (answer_id, comment_id) VALUES (2, 5);
INSERT INTO tag (text) VALUES ("data");
INSERT INTO tag (text) VALUES ("backup");
INSERT INTO tag (text) VALUES ("invoice");
INSERT INTO user_tag (user_id, tag_id) VALUES (1,1);
INSERT INTO user_tag (user_id, tag_id) VALUES (1,2);
INSERT INTO user_tag (user_id, tag_id) VALUES (1,3);
INSERT INTO user_tag (user_id, tag_id) VALUES (2,1);
INSERT INTO user_tag (user_id, tag_id) VALUES (2,2);
INSERT INTO user_tag (user_id, tag_id) VALUES (3,1);
INSERT INTO question_tag (question_id, tag_id) VALUES (1,1);
INSERT INTO question_tag (question_id, tag_id) VALUES (1,2);
INSERT INTO question_tag (question_id, tag_id) VALUES (2,1);
INSERT INTO question_tag (question_id, tag_id) VALUES (2,2);
INSERT INTO question_tag (question_id, tag_id) VALUES (3,3);
INSERT INTO vote(type, user_id, answer_id) VALUES (1, 3, 1);
INSERT INTO vote(type, user_id, answer_id) VALUES (2, 1, 1);